version: 2

jobs:
    build:
      machine: true
      steps:
        - checkout
        - run: wget -qO- get.nextflow.io | bash ; chmod 755 nextflow ; sudo ln -s ~/project/nextflow /usr/local/bin/ ; sudo apt-get install graphviz
        - run: cd ~ && git clone --depth=1 https://github.com/IARCbioinfo/data_test.git
        - run: echo " docker.runOptions = '-u $(id -u):$(id -g)' " > ~/.nextflow/config
        - run: cd ~/project ; docker build -t iarcbioinfo/platypus-nf .
        - run: nextflow run ~/project/platypus.nf -with-docker iarcbioinfo/platypus-nf --help
        - run: nextflow run ~/project/platypus.nf -with-docker iarcbioinfo/platypus-nf --input_folder ~/data_test/BAM/ --ref ~/data_test/REF/17.fasta
        - run: nextflow run ~/project/platypus.nf -with-docker iarcbioinfo/platypus-nf --input_folder ~/data_test/BAM/ --ref ~/data_test/REF/17.fasta --region BED/TP53_small.bed
        - run: nextflow run ~/project/platypus.nf -with-docker iarcbioinfo/platypus-nf --input_folder ~/data_test/BAM/ --ref ~/data_test/REF/17.fasta --compression
        - run: nextflow run ~/project/platypus.nf -with-docker iarcbioinfo/platypus-nf --input_folder ~/data_test/BAM/ --ref ~/data_test/REF/17.fasta --compression --filter
        - run: cd ; mv ~/nf-pipeline_info/platypus_dag.html ~/project/
        - deploy:
            branch: [dev, master]
            command: chmod +x deploy.sh && ./deploy.sh
